### ISSUE TITLE
temporal coupling between tests

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-python-driver#108]
Took me the better part of this morning to find out why simply adding a test to tests/test_views.py::TestBatchJobs caused some other tests to fail but it seems to boil down to tests depending on other tests.

Running all tests within the TestBatchJobs class returns successfully:
```
pytest tests/test_views.py::TestBatchJobs

==================================================================================================== 61 passed, 1 warning in 0.25s =====================================================================================================
```

Whereas running an individual test within the same class fails:
```
pytest tests/test_views.py::TestBatchJobs::test_download_result

======================================================================================================= short test summary info ========================================================================================================
FAILED tests/test_views.py::TestBatchJobs::test_download_result[0.4.0] - openeo_driver.testing.ApiException: Expected response with status code 200 but got 404. Error: {'code': 'JobNotFound', 'id': '095685f9-dd8b-4898-a6b7-a9ce22...
FAILED tests/test_views.py::TestBatchJobs::test_download_result[1.0.0] - openeo_driver.testing.ApiException: Expected response with status code 200 but got 404. Error: {'code': 'JobNotFound', 'id': '14c14d99-0909-472f-b2f9-101163...
===================================================================================================== 2 failed, 1 warning in 0.27s =====================================================================================================
```

Looks like test_download_result assumes that some other test before it initializes the JobRegistry (add job "07024ee9-7847-4b8a-b260-6c879a2b3cdc" to it and also mark it as finished).

This problem of temporal coupling is not limited to test_download_result.

**Comment by soxofaan** [comment]
I think I struggled with this too in the past and fixed it for a couple of cases in https://github.com/Open-EO/openeo-python-driver/commit/6a03f7683b12756901e93b8299b7fbb1f3f7e815  if I can reconstruct the situation a bit.
I guess I missed some more cases of coupling.
