### ISSUE TITLE
UDF debugging and logging

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#124]
Debugging/logging in and around UDF usage is not straightforward at the moment.

some things to tackle:

- functionality in client to allow logging from UDF code (e.g. https://github.com/Open-EO/openeo-python-client/issues/302)
- extra logging on driver side where UDFs are invoked
- make sure logging from UDF is visible in user logs

**Comment by bossie** [comment]
Invoking this UDF will add `inspect` log entries:

```python
# Load initial data cube.
s2_cube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={"west": 4.00, "south": 51.04, "east": 4.10, "north": 51.1},
    temporal_extent=["2022-03-01", "2022-03-31"],
    bands=["B02", "B03", "B04"]
)

# UDF code (as inline string)
udf_code = """
from openeo.udf import XarrayDataCube
from openeo.udf.debug import inspect

def apply_datacube(cube: XarrayDataCube, context: dict) -> XarrayDataCube:
array = cube.get_array()
inspect(data=len(array), message="len(array)", code="test_udf_logging", level="warning")
array.values = 0.0001 * array.values
return cube
"""

# Create UDF helper object encapsulating the UDF code.
udf = openeo.UDF(code=udf_code, runtime="Python", data={"from_parameter": "x"})

# Pass UDF object as child process to `apply`.
rescaled = s2_cube.apply(process=udf)

rescaled.execute_batch(out_format="GTiff")
```

Their log `level`, `message`, `data` and `code` are properly returned by the batch jobs logs API:
![udf_logs_response](https://user-images.githubusercontent.com/1032518/190416065-0886602d-5fad-4538-8c59-0a53f20ccec5.png)
