### ISSUE TITLE
Don't report GeoTiff output format

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#13]
http://openeo.vgt.vito.be/openeo/0.4.0/output_formats reports the file types `GeoTiff` and `GTiff`. According to the API this is not allowed: 

> Back-ends are MUST NOT support aliases, for example it is not allowed to support geotiff instead of gtiff. Nevertheless, openEO Clients MAY translate user input input for convenience (e.g. translate geotiff to gtiff).

Therefore, the back-end should remove `GeoTiff` from the list of output formats.

**Comment by soxofaan** [comment]
implementation done
(still to be deployed)
