### ISSUE TITLE
job registry based on ES

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#153]

**Comment by JanssenBrm** [comment]
Some more technical information

**Access**
The API is hosted at jobtracker.openeo.vgt.vito.be. The swagger docs are hosted at the _/docs_ endpoint.

**Authentication**
Some of the endpoints will create or update information in the database. These endpoints require a valid bearer token. 

The token to be added needs to be an OIDC token that is created through TerraScope. To support m2m communication, we've enabled the OIDC client credentials flow. The client credentials flow requires the following information:
* Issuer: https://sso.terrascope.be/auth/realms/terrascope
* Client ID: openeo-job-tracker

The resulting access token needs to be added to the _Authorization_ header of the requests using the following format: 
`Bearer <acess_token>`

**Comment by soxofaan** [comment]
(related internal ticket: FD-5452)

**Comment by soxofaan** [comment]
@JanssenBrm   can you give an example of a POST body for a `/jobs/search`  request? 
The docs just state "Query supported by ElasticSearch",  but I'm not sure how to use that. 
Also, the example value `{}`  gives a  "500 Internal Server Error Could not query jobs: empty query" error

**Comment by soxofaan** [comment]
@JanssenBrm  where can I find created jobs in ES? I managed to do a create requests without errors, and I now want to check my submitted data in ES/Kibana

**Comment by JanssenBrm** [comment]
> @JanssenBrm can you give an example of a POST body for a `/jobs/search` request? The docs just state "Query supported by ElasticSearch", but I'm not sure how to use that. Also, the example value `{}` gives a "500 Internal Server Error Could not query jobs: empty query" error

To provide the most flexibility for the API, you can use any JSON-based query supported by elasticsearch. More information is available at https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html. 

Example - Returning all the jobs 
```JSON
{
    "query": {
        "bool": {
            "must": [
                {
                    "match_all": {}
                }
            ]
        }
    }
}
```

Example - Returning all the jobs for user `foobar`
```JSON
{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "user_id": "foobar"
                    }
                }
            ]
        }
    }
}

**Comment by bossie** [comment]
Question while I'm going over this code in the context of https://github.com/Open-EO/openeo-geopyspark-driver/issues/325:

https://github.com/Open-EO/openeo-python-driver/blob/94b60f5f0b3eeb1782ee4cbe7522c10fdfc734be/openeo_driver/jobregistry.py#L185

Shouldn't this be `ElasticJobRegistryCredentials.get(env=environ)`?

**Comment by soxofaan** [comment]
> Shouldn't this be ElasticJobRegistryCredentials.get(env=environ)?

good point. However, I recently eliminated the use of `ElasticJobRegistry.from_environ`, so that code is actually unreachable and to be deleted

**Comment by soxofaan** [comment]
now that https://github.com/Open-EO/openeo-job-registry-elastic-api/issues/28 is fixed I think it is time to close this initial ticket, and leave the rest of the work for follow up tickets
