### ISSUE TITLE
backend returning logs without level

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#160]
This job: j-65b73756031c4955aadb3d42753de2e9 on creo, has logs with level set to 'TRACE'. This level is unknown to openEO, so empty level is returned, but this is not compliant with respect to the spec.
Proposed solution is not to return these logging lines.

**Comment by bossie** [comment]
This method's return type is a clear signal that, indeed, it is currently possible that log entries don't carry a level:

https://github.com/Open-EO/openeo-geopyspark-driver/blob/6252c69d391aa052bd4845d6d403c760e4448080/openeogeotrellis/logs.py#L82
