### ISSUE TITLE
detect coordinates/polygons in wrong CRS in geojson input

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#166]
A user was trying to invoke a UDP with a geojson parameter with coordinates in a projection system other than EPSG:4326.
This resulted in an unclear error, it would be better to detect this by checking if coordinates are in a reasonable bounds:
-360<=x<=360
-100<=y<=100
Ideally, this should already throw an error in a 'validate' call.

`
{"process": {"process_graph": {"CropSAR1": {"process_id": "CropSAR", "arguments": {"biopar_type": "FAPAR", "date": ["2022-01-01", "2022-12-31"], "polygon": {"type": "Polygon", "coordinates": [[[457666.2066643487, 6184112.621263116], [457666.2066643487, 6184312.621263116], [457866.2066643487, 6184312.621263116], [457866.2066643487, 6184112.621263116], [457666.2066643487, 6184112.621263116]]]}}, "namespace": "vito"}, "saveresult1": {"process_id": "save_result", "arguments": {"data": {"from_node": "CropSAR1"}, "format": "NetCDF", "options": {}}, "result": true}}}}`

Current stacktrace:

```
File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 111, in load_collection
    return self._load_collection_cached(collection_id, load_params, WhiteListEvalEnv(env,WHITELIST))
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/layercatalog.py", line 226, in _load_collection_cached
    target_epsg_code = auto_utm_epsg_for_geometry(box(west, south, east, north), srs)
  File "/opt/venv/lib64/python3.8/site-packages/shapely/geometry/geo.py", line 64, in box
    return Polygon(coords)
  File "/opt/venv/lib64/python3.8/site-packages/shapely/geometry/polygon.py", line 261, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/opt/venv/lib64/python3.8/site-packages/shapely/geometry/polygon.py", line 539, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 413, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: GEOSGeom_createLinearRing_r returned a NULL pointer
```

**Comment by JeroenVerstraelen** [comment]
Most places in the python driver that read a geojson from an external source now also validate if the coordinates are in the correct bounds. This includes: process_graphs, DelayedVectorCube and DriverVectorCube.

**Comment by soxofaan** [comment]
for cross reference reasons just reporting here as well: 
some integration tests fail due to this feature:

- .../openeo-integrationtests/1142/testReport/openeo-geopyspark-integrationtests.tests/test_integration/test_simple_raster_to_vector_1_1_0_/ 
	`openeo.rest.OpenEoApiError: [400] Internal: Failed to parse Geojson. Invalid coordinate: [551320.0, 5654280.0]. X value must be between -360 and 360, Y value must be between -100 and 100. (ref: r-0ddb4552f1774442805ef0b96078b7ce)`
- .../openeo-integrationtests/1142/testReport/nextland.tests.openeo_integrationtest/test_yield_potential_maps/testSESOutgaarden_1_0_0_terrascope_/ 
	`openeo.rest.OpenEoApiError: [400] Internal: Failed to parse Geojson. Coordinates are invalid. (ref: r-dcb33a8663b94405b978897cbbd21908)`
