### ISSUE TITLE
confusing User-Agent header in shared Session object

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-python-driver#217]
The EJR seems to modifiy an existing `Session`'s `User-Agent` header, making for some confusing logs (in this case, the HTTP calls originate from `openeogeotrellis.integrations.etl_api.EtlApi` instead).

![MicrosoftTeams-image](https://github.com/Open-EO/openeo-python-driver/assets/1032518/3b411ff3-af0d-4e6a-8b5b-c06a1b33c621)

**Comment by soxofaan** [comment]
https://github.com/Open-EO/openeo-python-driver/blob/4771bcc8ede3d7da1e4e01b375d16bc856ec9618/openeo_driver/jobregistry.py#L223-L228

indeed, this blindly sets user agent on the request session, regardless of who "owns" or created that session. Maybe the user agent should only be set if the session is created in  `ElasticJobRegistry.__init__`?

**Comment by soxofaan** [comment]
feel free to review and merge #221

**Comment by bossie** [comment]
Merged!
