### ISSUE TITLE
werkzeug vulnerability 

### ISSUE THREAD

**Issue by leotizzei** [Open-EO/openeo-python-driver#243]
Hi everyone,

I’ve recently seen this vulnerability (https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw) in Werkzeug lib. The patched versions are 2.3.8 and 3.0.1, but both clash with the constraints specified in the requirements, i.e.,  `"werkzeug>=1.0.1,<2.3.0"` ( https://github.com/Open-EO/openeo-python-driver/blob/182ead3c19b8971e420929f71977d0ac9d1eaa26/setup.py#L47C9-L47C33). I installed werkzeug 3.0.1 and ran the unit tests to explore if the upgrade of the werkzeug lib would cause some new errors. The upgrade did cause the failure of some test cases, due to the URL encoding (as described [here](https://github.com/Open-EO/openeo-python-driver/issues/187)). It was suggested to fix this by using `=` instead of `%3D`, but an alternative solution was implemented, which was to set "werkzeug<2.3.0". Given the above mentioned vulnerability issue, I wonder if it is time to reconsider this constraint. 

Thanks!

**Comment by soxofaan** [comment]
werkzeug is now bumped on master to `werkzeug>=2.3.8,<3.0.0` (https://github.com/Open-EO/openeo-python-driver/commit/549a82a4eb5183f5c01679c7da23c26be5544cf8)

**Comment by soxofaan** [comment]
now also lifted the werkzeug<3 constraint in master.

I think we can close this one now
