### ISSUE TITLE
wrong dimension name for collection CGS_SENTINEL2_RADIOMETRY_V102_001 ?

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-driver#25]
I am trying the evi process graph using this collection: CGS_SENTINEL2_RADIOMETRY_V102_001, which should have dimension "bands" according to its [metadata](http://openeo.vgt.vito.be/openeo/0.4.0/collections/CGS_SENTINEL2_RADIOMETRY_V102_001).

However when trying to reduce over "dimension": "bands" (or "spectral" or anything else), I get the following error:
```
{"message":"'list' object has no attribute 'reduce'"}
```

By running the [phenology example](https://github.com/Open-EO/openeo-python-client/blob/master/examples/phenology_example.py) and checking the pg produced, I saw that the correct value is "dimension": "spectral_bands".  Specifying that fixes the issue, but without the working example one would not know.

I'm aware that generally a user is not supposed to build the pg by hand, still it should be possible to do that. Did I miss this info anywhere in the metadata?

I can provide a full pg for testing if needed.

**Comment by soxofaan** [comment]
should be fixed by e6787860a93
