### ISSUE TITLE
Include request id and wall clock time in sync processing response headers

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#251]
came up while discussing PEOPLE-EA project:

Add request id in sync processing response headers 
(or all responses automatically)

**Comment by soxofaan** [comment]
cc @jdries @mbuchhorn

**Comment by soxofaan** [comment]
maybe also: header with (server side) elapsed wall clock time of sync processing, to help investigating performance

**Comment by bossie** [comment]
I already added this in the form of a `Request-Id` response header.

**Comment by soxofaan** [comment]
aha great, I didn't know that

```
curl -I https://openeo.vito.be/openeo/1.1/
HTTP/2 200 
...
request-id: r-240125f2460a4d7891fcfacbd31d098b
...
```

@mbuchhorn that might already be a useful thing for the k.lab people to include in their logging

**Comment by JeroenVerstraelen** [comment]
@soxofaan can this issue be closed?

**Comment by soxofaan** [comment]
adding the server side wall clock time in headers could be another thing to consider
but let's just close this for now indeed
