### ISSUE TITLE
mask_scl_dilation still uses old data types

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-python-driver#264]
The `scl_mask_dilation` process still uses a subtype of `raster-cube` instead of `datacube`.

This causes the CDSE editor to report the following warning: `Incoming data type is not compatible for parameter "data"`. 
The warning is also shown in a process graph: 
![image](https://github.com/Open-EO/openeo-python-driver/assets/33786515/522923b8-4621-402d-a730-2aa166110297)

**Comment by jdries** [comment]
was trivial, fixed it. Now it basically will break for users of old version, but by default clients will select the newer versions anyway.

**Comment by VictorVerhaert** [comment]
I am encountering the same error again with the `mask_scl_dilation` process in de CDSE editor.
Has this fix been deployed on production yet?
![image](https://github.com/Open-EO/openeo-python-driver/assets/33786515/9cf40eef-0531-4891-8afe-4aae0977e134)

**Comment by soxofaan** [comment]
yes this just a matter of promoting latest changes to production CDSE
