### ISSUE TITLE
connection.job(<job_id>) errors

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-python-driver#285]
I am using a python notebook to start an openeo batch job, which can take multiple hours. Therefore, I close the notebook and want to reload the job afterwards with 

```
conn = openeo.connect("openeo.cloud").authenticate_oidc()
job = conn.job("eodc-98132089-1fae-4e34-87ef-db66cb1c0e74")
print(job.status())
```
which results in 
```
OpenEoApiError 
----> [1] print(job.status())
... 
File ~/.cache/pypoetry/virtualenvs/py3.11/lib/python3.11/site-packages/openeo/rest/job.py:74, in BatchJob.describe(self)
...
return self.connection.get(f"/jobs/{self.job_id}", expected_status=200).json()
...
    [195]         )
    [197] # Failed to parse it as a compliant openEO API error: show body as-is in the exception.
    [198] text = response.text

OpenEoApiError: [500] Internal: Server error: AssertionError() (ref: r-2405297a9b8c46a68960cc8401d46360)

```
 I am not sure which url is used in `self.connection.get(f"/jobs/{self.job_id} ... "`, but I think this is an endpoint on `openeo.cloud`, isn't it? 

when connecting to the `openeo.eodc.eu` directly, the `conn.job("...")` works well.
Is there anything to update on the eodc-backend side to make this available again?

**Comment by soxofaan** [comment]
regardless, are you sure this only happens when "re-attaching" to a job with `conn.job("eodc-98132089-1fae-4e34-87ef-db66cb1c0e74")`?  I think this problem should also happen with jobs that finish in a single notebook run.

**Comment by soxofaan** [comment]
Can you try out the dev instance of the openEO Platform aggregator at https://openeocloud-dev.vito.be/ ?
That `Internal: Server error: AssertionError` should not happen there

**Comment by ValentinaHutter** [comment]
Thanks for looking into this, there is a public holiday in Austria today - so I will be back in the office on Monday, then I will check and let you know! :)

**Comment by ValentinaHutter** [comment]
> Can you try out the dev instance of the openEO Platform aggregator at https://openeocloud-dev.vito.be/ ? That `Internal: Server error: AssertionError` should not happen there

I can confirm, it is working on the dev instance! Thank you!

**Comment by bschumac** [comment]
@soxofaan is the fix also deployed to prod? We still see an error.

**Comment by soxofaan** [comment]
The fix should now be active on openeo.cloud. Can you confirm it works now?

**Comment by ValentinaHutter** [comment]
Yes, it is working for me now, thank you!
