### ISSUE TITLE
Installation improvements

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-driver#29]
I installed the driver locally and ran into a few issues/inconveniences, which I just wanted to document here without any urgent need for solving:

- A requirements file would be helpful for automatically installing the necessary python modules, I took them from "setup.py".

- I ran into some issues with the pip version of the "openeo" package (0.0.9). Installing the latest python client version from Github solved it (so there might be a version constraint necessary).

- Some instructions on necessary files in the "data" folder would be nice I needed some errors and code searching to find out where to put things (e.g. processes, api)

- I also couldn't make gunicorn to run it in "productive" mode, but that might be an issue of wrong dependency versions.

**Comment by soxofaan** [comment]
@bgoesswe   I pushed some README updates about that
can you check if that addresses your problems?

**Comment by soxofaan** [comment]
> requirements file would be helpful

`setup.py` is actually easier in this case because you only have to do `pip install .` (or something similar) instead of `pip install -r requirements.txt` + `pip install .`

> issues with the pip version of the "openeo" package

you need an additional `--extra-index-url`  when doint `pip install` (See readme)

> instructions on necessary files in the "data" folder

these are git submodules (see readme)

**Comment by bgoesswe** [comment]
Thanks, yes I tried it again following the new README and it worked fine!
