### ISSUE TITLE
Default batch job log level

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#294]
https://github.com/Open-EO/openeo-python-driver/blob/e1bb7712e66b704077548c95e1c41eb143032b2c/openeo_driver/views.py#L1474-L1478

openEO spec specifies INFO level as default, but we leave it undefined, causing DEBUG logs to be included by default, which slows down working with logs, e.g. in the web editor

**Comment by soxofaan** [comment]
> openEO spec specifies INFO level as default

correction: default level is DEBUG, but that is not clear from current docs. Also see https://github.com/Open-EO/openeo-api/commit/6ea99c3ae4ab342c54f9cd39a7403085fa6ca79f

**Comment by soxofaan** [comment]
On the other hand, the default minimum log level when **creating** a jobs (`min_log_level_default`) is INFO, while we probably log everything

**Comment by jdries** [comment]
Not sure if that is correct: when explicitly requesting debug logging in our batch jobs, a lot more is logged.
I think  that we correctly provide 'INFO' logging for the moment, with some exceptions where debug logging is explicitly included.

**Comment by soxofaan** [comment]
indeed this issue has been resolved
