### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#30]
The API requires HTTPS (instead of HTTP) for the API as authentication credentials with HTTP Basic, OAuth2 and OpenID Connect are transmitted without encryption to the server so they can "easily" be sniffed by a third-person. Therefore the WCPS driver should support HTTPS and the deployed instance should activate it by default.

Another issue is, that the Web Editor, which is deployed with HTTPS can't connect to HTTP back-ends due to browsers forbidding "mixed content" (i.e. forbidding insecure HTTP connections being established by secure/HTTPS web pages). Providing the Web Editor with HTTP would promote insecure workflows and therefore is not desirable.

**Comment by soxofaan** [comment]
I already pushed a first fix, but have to double check when it is actually deployed

**Comment by christophfriedrich** [comment]
What is the status of this one? 🙂 
The well-known document still lists HTTP links but the individual backends forward to HTTPS 🤔

**Comment by soxofaan** [comment]
It is fixed in dev but has not been promoted to production so far.

There are quite some changes in dev compared to current prod (related to 1.0 support). We want to double check that some  depending on 0.4 don't break

**Comment by soxofaan** [comment]
we managed to deploy a new production instance

https://openeo.vito.be/.well-known/openeo now lists https links

**Comment by m-mohr** [comment]
Great, should be updated in the Hub tonight.

**Comment by m-mohr** [comment]
Unfortunately, I need to reopen this. 
https://openeo.vgt.vito.be/.well-known/openeo is giving an error although http://openeo.vgt.vito.be/.well-known/openeo gives a proper response. https should also work on the well-known doc.

**Comment by jdries** [comment]
Hi Matthias,
Can you try this link for https:
https://openeo.vito.be/.well-known/openeo
It does not contain the '.vgt', so domain is slightly different, so a bit confusing. The https link can be considered our production url. (We keep the other endpoint around in case we want to test issues with proxying.)

**Comment by m-mohr** [comment]
Thanks, works, but not in JS, see #41 :-)
