### ISSUE TITLE
Support API 0.4 and 1.0 from same codebase?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#31]
API version 1.0 is now almost stable and the way forward, but at VITO we want to keep support for 0.4 API for some time because we have some applications/users depending on it and we can not port them all at once.

Until now (with versions 0.3, 0.4) we tried to provide multiple version support from same openeo-python-driver codebase, but that made things sometimes bit ugly (e.g. see #17).

The API diff between 0.4 and 1.0 is quite large and we might want to reconsider this single code base approach. Alternative: fork off a "0.4" branch for maintenance of the 0.4 feature set and keep the master branch 1.0-only. Then, run separate backend instances for 0.4 and 1.0 API.

This ticket is meant to discuss this idea and the respective disadvantages/advantages

**Comment by soxofaan** [comment]
A problem I'm having at the moment: in python driver we use git submodules to stay close to API specification (e.g error codes) and process specifications, but to handle multiple API versions at same time, we have to include separate submodules for each API version we want to support, which can become cumbersome. See #32

**Comment by m-mohr** [comment]
What's the issue to include multiple submodules set to specific tags? The openeo.org repo does it for documentation purposes and it works without issues. :-)

**Comment by soxofaan** [comment]
the git submodules themselves are not the problem indeed, but its the fact that there is "global functionality" that assumes a certain/single version (e.g. the exception classes are derived from the error codes from the API). While it is technically possible to make these things version dependent, it will make things more complex (= brittle and harder to maintain). We've already seen this with the 0.3->0.4 API upgrade.

**Comment by soxofaan** [comment]
for an internal ticket (EP-3278) I used an approach with versioned submodules (#32 ):
- The OpenEO error exception classes are now tied to API 1.0. So even when using 0.4 API you get error codes from 1.0 API, but that is not a huge problem I think as these codes are self-describing enough.
- The process descriptions (GET `/processes`) now properly depend on API version

**Comment by soxofaan** [comment]
going to close this ticket (we decided to support 0.4 and 1.0 simultaneously at the moment), 
and created a dedicated ticket about dropping 0.4 support (somewhere in future): #47
