### ISSUE TITLE
API 1.0 support

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#33]
ticket for grouping tagging small generic API 1.0 related issues

**Comment by soxofaan** [comment]
Corresponding ticket for openeo python client: Open-EO/openeo-python-client#125

**Comment by m-mohr** [comment]
It seems there's a 1.0.0 instance running, but it's not listed yet in the well-known document. :-)

**Comment by soxofaan** [comment]
just finished a internal ticket (EP-3278) about compliance of `GET /processes` 
also handled some important process renames like `reduce_dimension`, `aggregate_spatial` and `mask_polygon`

**Comment by soxofaan** [comment]
Time to close this ticket
API 1.x has been sole focus for long time now
