### ISSUE TITLE
Support paging in job listings

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#332]
We're getting in trouble with user job listings getting too large, so we need to implement paging in job listings

related to and dependency for problem in geopyspark driver
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/959

**Comment by soxofaan** [comment]
I also noted that pagination is actually driven from client side (through `limit` parameter):
- https://github.com/Open-EO/openeo-api/issues/550

while we want to enforce pagination from backend-side here, so there is a bit of conflict at first sight

**Comment by soxofaan** [comment]
related issues:


- https://github.com/Open-EO/openeo-api/issues/550
- https://github.com/Open-EO/openeo-web-editor/issues/331
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/959
- https://github.com/Open-EO/openeo-aggregator/issues/164
- https://github.com/Open-EO/openeo-python-client/issues/677

**Comment by soxofaan** [comment]
This pull request should cover the part in the python driver:
- https://github.com/Open-EO/openeo-python-driver/pull/333

but I'll wait to merge and first verify that it is enough to cover the needs of https://github.com/Open-EO/openeo-geopyspark-driver/issues/959

**Comment by m-mohr** [comment]
Here's a list of things that can be paginated:

- [ ] GET /collections
- [ ] GET /processes
- [ ] GET /jobs
- [ ] GET /process_grapg
- [ ] GET /files
- [ ] GET /services
- [ ] Logs (Services and Jobs)
- [ ] Collection Items (if implemented)

**Comment by soxofaan** [comment]
Already merged #333 with 4747fa258376cc76c206d8a1292727e6ae5f075d and did some follow up fixes

companion feature branch in geopyspark driver is now also merged with https://github.com/Open-EO/openeo-geopyspark-driver/commit/ac18e220f945204008095af862e64c294f7e4e51

**Comment by soxofaan** [comment]
as mentioned in https://github.com/Open-EO/openeo-geopyspark-driver/issues/959#issuecomment-2523460195:

paging support is now just deployed to CDSE dev and works there:

```
>>> connection.get("/jobs", params={"limit": 3, "page": 1}).json()
{'jobs': [
  {'id': 'j-241119233b06409aa3e739d58330caa0', ...}
  {'id': 'j-2411193d9701425a92426664cb984de2', ...}
  {'id': 'j-241119d9ff504e28b1a9f59d8e1a2f50', ...}
],
 'links': [
   {'rel': 'next', 'href': 'https://openeo......copernicus.eu/openeo/1.2/jobs?limit=3&page=2'}
 ]}
```
Only 3 jobs are listed (from total of a lot more), and there is a link to the next "page"

**Comment by m-mohr** [comment]
@soxofaan I tested this a bit and found a couple of things that doesn't seem right:

https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1 => returns a next link with href `https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=1` - shouldn't that be `page=2` (the next page shows the right jobs, it's just the 0-based pages that feel a bit unnatural)?

https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=1 => returns a next link with href `https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=2` => That link should not exist because https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=2 returns an empty job list

**Comment by soxofaan** [comment]
> The next page shows the right jobs, it's just the 0-based pages that feel a bit unnatural.

Indeed, we use 0-based indexing of the pages because that's what the database layer provides us. We could translate that to 1-based indexing, but that's at best just something cosmetic and at worst, it makes things more error prone and confusing. The openEO API does not prescribe how paging should be organized in terms of query parameters, so the user is not expected to interact with this implementation detail. 

Note that in an initial implementation I even played with some additional b64 encoding (e.g. to be able to handle more complex data structures than just a single integer) making the page parameter look like `&page=eyJwYWdlIjo0LCJzaWduIjoic2Rmd2UzcmZlIn0%3D`. For the geopyspark driver I dropped that idea, but this will be necessary on the level of the aggregator where I'll have to figure out some system to combine multiple page sequences to a single page sequence.


if `page=0` for the first page is indeed too weird, we could also consider renaming the parameter to e.g. `p=0`, `p0=0` `pageindex=0`, or `pi=0`

**Comment by soxofaan** [comment]
> next link with href `https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=2` => That link should not exist because `https://openeo-dev.vito.be/openeo/1.2/jobs?limit=1&page=2` returns an empty job list

hmm that must be a bug at database layer too, because there we just return the next page according to the db (https://github.com/Open-EO/openeo-job-registry-elastic-api). Maybe there is a shortcut there that guesses there are still pages to come when the result set has exactly `limit` items. If you use `limit=1` that guess will always be one-off.   Do you also get that problem when you use a more practical limit like 10 or 100?

**Comment by soxofaan** [comment]
cc @JanssenBrm for 
- >  we use 0-based indexing of the pages because that's what the database layer provides us.
- > Maybe there is a shortcut there that guesses there are still pages to come when the result set has exactly `limit` items

**Comment by m-mohr** [comment]
Yeah, the 0-based pages are fine for the API. It just felt weird and wasn't sure whether that might be the issue for the last empty page.

I think I remember a similar issue in STAC where ElasticSearch wasn't able to determine whether there are more results and as such also always returned an additional empty last page. Maybe grab limit+1 results and determine based on the existance of that additional element whether to add the next link? Not sure whether that has other side-effects though.

**Comment by m-mohr** [comment]
Opened #350 to keep track
