### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#41]
For https://openeo.vito.be/.well-known/openeo no CORS headers are sent:
> Access to XMLHttpRequest at 'https://openeo.vito.be/.well-known/openeo' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Thus no browser-based tool can access the back-end. Interestingly, http://openeo.vgt.vito.be/.well-known/openeo works, but https://openeo.vgt.vito.be/.well-known/openeo doesn't work again (and shouldn't be used according to #30).

**Comment by soxofaan** [comment]
Known issue, and already fixed (in internal bootstrap script, so I can't cross-reference it).

Not deployed yet at the moment, but that should happen in the next days

**Comment by soxofaan** [comment]
(internal ticket: EP-3033)
