### ISSUE TITLE
Use "signed" URLs for job result assets (instead of requiring header based auth)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#50]
(Reported by @przell and @m-mohr )

The asset URLs for batch job results in VITO backend require bearer authentication:
https://github.com/Open-EO/openeo-python-driver/blob/104a74126628860d1fa3715a82a3014cc3792b2c/openeo_driver/views.py#L629-L632

The API however specifies that:
> The URLs SHOULD be available without authentication so that external clients can download them easily. If the data is confidential, signed URLs SHOULD be used to protect against unauthorized access from third parties.

**Comment by jdries** [comment]
I tested again after deploying to prod yesterday.
In the web editor, the result of an old batch job now gave me a signed url:
https://openeo.vito.be/openeo/1.0/jobs/49138d94-2944-4bf0-8315-15af590c38c9/results/ZHJpZXNq/ea5e372be1812d942389f41ef831af37/openEO_2017-03-07Z.tif?expires=1626846136

I could download this url using curl, without additional auth.

If you still see issues, please include the actual url, so we can verify if it is signed or not. (Unsigned url's still work and require auth.)

**Comment by m-mohr** [comment]
Works for me, thanks.
