### ISSUE TITLE
CORS on the "validation" endpoint

### ISSUE THREAD

**Issue by jneijt** [Open-EO/openeo-python-driver#51]
When validating a process graph by calling the `/validation` endpoint, the request is blocked due to missing CORS headers. Interestingly, the OPTIONS request correctly includes all required CORS headers but the POST request afterwards does not.

```
Access to XMLHttpRequest at 'https://openeo-dev.vito.be/openeo/1.0/validation' from origin 'https://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Would it be possible to enable CORS on the validation endpoint as well? We use it to check if a back end might support the requested processing in the mobile app.

**Comment by jneijt** [comment]
Interesting, I got a 200 response and at the same time telling me it was blocked due to CORS headers missing. But I guess that's specific to the mobile app/development version then. Thanks for the clarification.

Good point with the capabilities not listing the `/validation` endpoint, I'll add a line checking if it's listed there and use it accordingly, that works for me 👍 

Unless you want to keep this around, I'm fine with closing the issue.

**Comment by soxofaan** [comment]
We already support CORS on `/validation` even though it does not exist :smile_cat:  so no need to keep this open
