### ISSUE TITLE
Synchronous download comes without extension

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-python-driver#53]
When executing a synchronous call ("run now") on the vito webeditor the result (downloaded file) is merely named "download". There is no extension added. See here:
![image](https://user-images.githubusercontent.com/51962348/97582971-af61bf00-19f6-11eb-9fba-c386cb23d703.png)

**Comment by m-mohr** [comment]
Re-opened this as I'm getting the Content-Type header application/octet-stream from VITO for a GeoTiff file, which indeed leads to no extension again. So back to the roots ;-)

**Comment by soxofaan** [comment]
VITO backend will now send better mime type headers. (not in production at the moment)
