### ISSUE TITLE
Requesting processes very slow

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-driver#62]
Connecting to the VITO back-end is very slow right now. 
For me, it takes around 1,5 minutes until the /processes endpoint has fully returned the data.
This is rather annoying, especially in the Web Editor where the processes are requested upfront.

I guess this is due to the mask_scl_dilation being so large? Maybe it would be a good idea to not return the "process_graph" property for pre-defined processes, where this is not very useful anyway.

**Comment by soxofaan** [comment]
> Anyway, maybe it's still a good idea to remove process graphs from pre-defined processes to make initial requests faster? 

that's certainly possible (e.g. by default), but there is not standardized way to get the process graph if you want it. 
For example with collections you have the "basic metadata" (all collections listing) and "full metadata" (single collection) views, but for pre-defined processes there is only one view: the "all processes" listing.

**Comment by m-mohr** [comment]
While that is true, for pre-defined processes the use cases where you'd need the process graph seem very limited. With https://github.com/Open-EO/openeo-api/pull/348 you'd get such an endpoint to get the full process description.

Anyway, I've tested connecting to VITO via the university VPN and there it's much faster (like 2 secs). That's not fast, but okay.
I'm really puzzled what makes the request so slow through my internet provider (Telekom) while it works with the same connection just tunneled through a VPN. So speed can't be the issue. Strange...
