### ISSUE TITLE
Configurability: move `app` building inside a function

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#69]
Currently openeo_driver builds the flask app at module top level of `openeo_driver.views`, which is the basic structure you find in every flask tutorial:

    from flask import Flask

    app = Flask(__name__)

    @app.route("/")
    def index():
         return "hello world"

This is nice and easy to get started for simple applications, but complicates things for more complex ones, like the openeo web app. Because the app is built at "import time", quite some components have to be available at import time already. Triggering a lot of logic at import time causes some challenges, including:
- getting import order right (e.g. circular dependency issues)
- hard to plug in configuration opportunities. E.g. we have to resort to env vars like `DRIVER_IMPLEMENTATION_PACKAGE`  for quite vital configuration parameters. Env vars are not always the nicest tools to finetune your app.
- (unit) testing: you sometimes need some dirty tricks to get testable components. This is especially tricky because because import time logic can only be done once in Python, so the flask app is a singleton which is annoying in unit test situations.

I think we should move the flask app building (so basically the whole of `openeo_driver.views`) inside a function (or break it up in more modular functions), this will simplify configuration and testing.

From the flask docs https://flask.palletsprojects.com/en/1.1.x/config/#configuration-best-practices :
> Configuration Best Practices
> Create your application in a function ... That way you can create multiple instances of your application with different configurations ...  You can use this to pass in configuration as needed.
> Do not write code that needs the configuration at import time.

**Comment by jdries** [comment]
Sounds logical enough. You could also have a look at the EODC driver for inspiration:
https://github.com/Open-EO/openeo-eodc-driver/tree/master/services
it splits up the API into a lot more separate (micro)services.

**Comment by soxofaan** [comment]
implemented in openeo-python-driver and now also adapted in openeo-geopyspark-driver
