### ISSUE TITLE
Issues with passing geometries to aggregate_spatial, CSV export

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-python-driver#70]
When I aggregate spatially with a MultiPolygon (via _python_ client), only one set of values is returned in CSV export. I'm not sure where this happens (aggregation or export), but I would expect all geometries in the exported file.

Example:
`{
  "process_graph": {
    "loadcollection1": {
      "arguments": {
        "bands": [
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "west": 5.590152740478516,
          "south": 52.66951218928503,
          "east": 5.753231048583984,
          "north": 52.75686657942532
        },
        "temporal_extent": [
          "2021-04-26",
          "2021-04-30"
        ]
      },
      "process_id": "load_collection"
    },
    "aggregatespatial1": {
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "geometries": {
          "coordinates": [
            [
              [
                [
                  5.645427,
                  52.702368
                ],
                [
                  5.6568,
                  52.702446
                ],
                [
                  5.645728,
                  52.716356
                ],
                [
                  5.645427,
                  52.702368
                ]
              ]
            ],
            [
              [
                [
                  5.67,
                  52.73
                ],
                [
                  5.682,
                  52.699
                ],
                [
                  5.645,
                  52.693
                ],
                [
                  5.67,
                  52.73
                ]
              ]
            ]
          ],
          "type": "MultiPolygon"
        },
        "reducer": {
          "process_graph": {
            "mean1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "aggregate_spatial"
    },
    "saveresult1": {
      "arguments": {
        "data": {
          "from_node": "aggregatespatial1"
        },
        "format": "CSV",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

Additionally, when I try to aggregate with a feature collection (directly from geojson.io, via _javascript_ client @m-mohr), I get the error `list index out of range`.

Example:
`{
  "process_graph": {
    "loadco1": {
      "arguments": {
        "bands": [
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "west": 4.320287704467773,
          "south": 50.8050668687832,
          "east": 4.392900466918944,
          "north": 50.84215341242185
        },
        "temporal_extent": [
          "2020-06-01",
          "2020-09-01"
        ]
      },
      "process_id": "load_collection"
    },
    "aggreg1": {
      "arguments": {
        "data": {
          "from_node": "loadco1"
        },
        "geometries": {
          "features": [
            {
              "geometry": {
                "coordinates": [
                  [
                    [
                      4.363503456115723,
                      50.83242375662908
                    ],
                    [
                      4.3399858474731445,
                      50.82705667183455
                    ],
                    [
                      4.369468688964844,
                      50.81493780212673
                    ],
                    [
                      4.363503456115723,
                      50.83242375662908
                    ]
                  ]
                ],
                "type": "Polygon"
              },
              "properties": {},
              "type": "Feature"
            }
          ],
          "type": "FeatureCollection"
        },
        "reducer": {
          "process_graph": {
            "mean1": {
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "process_id": "mean",
              "result": true
            }
          }
        }
      },
      "process_id": "aggregate_spatial"
    },
    "savere1": {
      "arguments": {
        "data": {
          "from_node": "aggreg1"
        },
        "format": "CSV"
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

Just overall I don't understand how exactly geometries need to be passed here.

**Comment by soxofaan** [comment]
I think all issues here are addressed:

> When I aggregate spatially with a MultiPolygon (via python client), only one set of values is returned in CSV export. 

As noted above, a MultiPolygon is considered to be a single geometry, so only a single aggregation is returned

To achieve a multi-geometry result, one should use a FeatureCollection (and currently it is also possible with a GeometryCollection on the VITO backend, but that is subject to change, see Open-EO/openeo-processes#253)

> when I try to aggregate with a feature collection, I get the error list index out of range.

Fixed this issues in CSV export logic in 7c47e11 
fix still has to be deployed to production,  but current workarounds are: 
- export to JSON instead of CSV, 
- or request multiple bands  instead of only "B08" (because bug was in the single band code path)
